---
new_page_extension: md
auto_deploy: false
admin_path: app/admin
webhook_url: 
sections:
- type: directory
  path: app/_posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - blog
- type: directory
  path: app/_pages
  label: Pages
  create: documents
  match: "**/*"
- type: directory
  path: app/_books
  label: Books
  create: all
  match: "**/*"
- type: directory
  path: app/_games
  label: Games
  create: all
  match: "**/*"
- type: directory
  path: app/_wiki
  label: Wiki
  create: all
  match: "**/*"
  templates:
  - wiki
upload_dir: app/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
