sudo: required
services:
- docker
before_install:
- pip install ansible==2.3.2.0
before_script:
- ENV=PROD bundle exec jekyll build
script:
- docker build -t atem18/kmdotnet:$TRAVIS_COMMIT .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push atem18/kmdotnet:$TRAVIS_COMMIT
before_deploy:
- openssl aes-256-cbc -K $encrypted_d7452885b0d3_key -iv $encrypted_d7452885b0d3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: cd ansible && ansible-playbook -i hosts --limit=www.kevin-messer.net -u
    kmdotnet -b --extra-vars "TRAVIS_COMMIT=$TRAVIS_COMMIT" kmdotnet.yml
