language: python
branches:
  only:
    - master
services:
  - docker
stages:
  - build
  - deploy
jobs:
  include:
    - stage: build
      install: skip # bundle install is not required
      script: skip
      build:
        skip_cleanup: true
        provider: script
        script: ./build.sh
    - stage: deploy
      install: skip # bundle install is not required
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script: ./deploy.sh
