language: ruby
cache: bundler
exclude: [vendor]
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
services:
  - docker
stages:
  - build
  - test
  - deploy on testing
  - deploy on staging
  - deploy on production
jobs:
  include:
    - stage: build
      script: ENV=PROD bundle exec jekyll build
    - stage: test
      script: ENV=PROD bundle exec htmlproofer ./_site
    - stage: deploy on testing
      deploy:
        script: ./deploy.sh
        on:
          branch: develop
    - stage: deploy on staging
      deploy:
        script: ./deploy.sh
        on:
          branch: content
    - stage: deploy on production
      deploy:
        script: ./deploy.sh
        on:
          branch: master