sudo: required
dist: trusty
language: ruby
cache: bundler
exclude: [vendor]
services:
  - docker
before_script:
  - ENV=PROD bundle exec jekyll build
script:
  - docker build -t atem18/kmdotnet:$TRAVIS_COMMIT .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push atem18/kmdotnet:$TRAVIS_COMMIT
before_deploy:
  - openssl aes-256-cbc -K $encrypted_d7452885b0d3_key -iv $encrypted_d7452885b0d3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: cd _ansible && docker run --rm \
    -v /tmp/deploy_rsa:/root/.ssh/id_rsa \
    -v $(pwd):/ansible/playbooks \
    atem18/ansible-playbook \
    -i www.kevin-messer.net, \
    --extra-vars "TRAVIS_COMMIT=$TRAVIS_COMMIT" \
    kmdotnet.yml
