sudo: required

services:
  - docker

before_install:
  - pip install ansible

before_script:
  - ENV=PROD bundle exec jekyll build
  - docker build -t atem18/kmdotnet:$TRAVIS_COMMIT .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push atem18/kmdotnet:$TRAVIS_COMMIT

script:
  - cd ansible && ansible-playbook -i hosts --limit=www.kevin-messer.net -u kmdotnet -b --extra-vars "TRAVIS_COMMIT=$TRAVIS_COMMIT" kmdotnet.yml