title: Kevin Messer
email: contact@kevin-messer.net
description: Welcome to my personal website
baseurl: ""
url: ""
twitter_username: atem18
github_username: atem18
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-admin
include: ["_pages"]
collections:
  my_collection:
    foo: bar
defaults:
  - scope:
      path: ""
      type: my_collection
    values:
      layout: page