title: Kevin Messer
email: contact@kevin-messer.net
description: Welcome to my personal website
baseurl: ""
url: ""
twitter_username: atem18
github_username: atem18
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-admin
include: ["_pages"]
collections:
  wiki:
    output: true
    permalink: /wiki/:path/
google_analytics: UA-41355039-1