version: '3'
services:
  traefik:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api)
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik
  kmdotnet:
    build: .
    restart: unless-stopped
    networks:
      - web
      - default
    labels:
      - "traefik.backend=kmdotnet"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:www.local.kevin-messer.net"
      - "traefik.enable=true"
      - "traefik.port=80"

networks:
  web:
    external: true