version: 2.1
executors:
  jekyll-builder:
    environment:
      JEKYLL_ENV: production
      NODE_ENV: production
      NOKOGIRI_USE_SYSTEM_LIBRARIES: "true"
    docker:
      - image: cimg/ruby:2.7.3-node
  aws-cli:
    docker:
      - image: cibuilds/aws:1.19.60
jobs:
  build:
    executor: jekyll-builder
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler
      - run:
          name: Install dependencies
          command: cd app && npm i && bundle install
      - run:
          name: Build the Jekyll site
          command: cd app && bundle exec jekyll build --config _config.yml
      - run:
          name: Test the Jekyll site
          command: cd app && bundle exec htmlproofer --http-status-ignore "999" --url-ignore "/atemlire.io/" _site
      - persist_to_workspace:
          root: ./
          paths:
            - app/_site
  deploy:
    executor: aws-cli
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Deploy _site
          command: aws s3 sync app/_site s3://www.atemlire.io --delete --cache-control max-age=14400
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
