version: 2.1
executors:
  jekyll-builder:
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    docker:
      - image: jekyll/builder:4.0
  aws-cli:
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    docker:
      - image: mesosphere/aws-cli
jobs:
  build:
    executor: jekyll-builder
    steps:
      - checkout
      - run:
          name: Test
          command: ls -lah && pwd && uname -a
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: Build jekyll website
          command: ENV=PROD bundle exec jekyll build
      - persist_to_workspace:
          root: ./
          paths:
            - _site
  deploy:
    executor: aws-cli
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Deploy _site
          command: ./aws.sh s3 sync ./_site s3://kmdotnet-s3bucket-1ucv72i21hs6g
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
