version: 2.1
  executors:
    docker-publisher:
      environment:
        IMAGE_NAME: atem18/kmdotnet
      docker:
        - image: circleci/buildpack-deps:stretch
  executors:
    aws-cli:
      environment:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      docker:
        - image: mesosphere/aws-cli
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Create temp container
          command: id=$(docker create atem18/kmdotnet)
      - run:
          name: Copy _site to local path
          command: docker cp $id:/srv/jekyll/_site .
      - run:
          name: Remove temp container
          command: docker rm -v $id
      - persist_to_workspace:
          root: .
          paths:
            - ./_site
  deploy:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Deploy _site
          command: ./aws.sh s3 sync _site s3://kmdotnet-s3bucket-1ucv72i21hs6g
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
