version: 2
jobs:
  build:
    docker:
      - image: jekyll/builder:4.0
    working_directory: /srv/jekyll
    environment:
      - JEKYLL_ENV=production
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      - JOB_RESULTS_PATH=run-results
    steps:
      - checkout
      - run:
          name: Build site
          command: jekyll build
      - run:
          name: Index with Algolia
          command: jekyll algolia
      - store_artifacts:
          path: run-results/
          destination: run-results
      - persist_to_workspace:
          root: ./
          paths:
            - _site
  deploy:
    docker:
      - image: circleci/python:3.7
    environment:
      S3_BUCKET_NAME: kmdotnet-s3bucket-1ucv72i21hs6g
    working_directory: ~/jekyll
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install awscli
          command: pip install awscli --upgrade --user
      - run:
          name: Upload to s3
          command: ~/.local/bin/aws s3 sync ./_site s3://$S3_BUCKET_NAME/ --delete --acl public-read
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
