version: 2.1
orbs:
  ruby: circleci/ruby@1.0.2
executors:
  jekyll-builder:
    working_directory: ~/kmdotnet
    environment:
      JEKYLL_ENV: production
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    docker:
      - image: cimg/ruby:2.7.1-node
  aws-cli:
    docker:
      - image: cibuilds/aws:1.18.87
jobs:
  build:
    working_directory: ~/repo
    executor: jekyll-builder
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build --config _config.yml
      - persist_to_workspace:
          root: ./
          paths:
            - _site
  deploy:
    working_directory: ~/repo
    executor: aws-cli
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Deploy _site
          command: aws s3 sync _site s3://kmdotnet-s3bucket-1ucv72i21hs6g --delete
      - run:
          name: Invalidate cache for non-www
          command: aws cloudfront create-invalidation --distribution-id E1ZZFI3OO0FZA8 --paths "/*"
      - run:
          name: Invalidate cache for www
          command: aws cloudfront create-invalidation --distribution-id E2QG9YBHY9LBBS --paths "/*"   
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
