version: 2.1
references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
executors:
  jekyll-builder:
    working_directory: ~/kmdotnet
    environment:
      JEKYLL_ENV: production
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      JOB_RESULTS_PATH: run-results
    docker:
      - image: circleci/ruby:2.6.3-buster-node
  aws-cli:
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    docker:
      - image: mesosphere/aws-cli
jobs:
  build:
    working_directory: ~/repo
    executor: jekyll-builder
    steps:
      - checkout
      - *attach_workspace
      - restore_cache:
          key: kmdotnet-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: kmdotnet-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
      - run:
          name: Create results directory
          command: mkdir -p $JOB_RESULTS_PATH
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build --config _config.yml 2>&1 | tee $JOB_RESULTS_PATH/build-results.txt
      - persist_to_workspace:
          root: ./
          paths:
            - _site
  deploy:
    working_directory: ~/repo
    executor: aws-cli
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Deploy _site
          command: ./aws.sh s3 sync _site s3://kmdotnet-s3bucket-1ucv72i21hs6g
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
