# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en"
title                    : "Atemlire"
title_separator          : "-"
name                     : "Kevin Messer"
description              : "My personnal website mostly about technology, games and books."
url                      : "https://www.atemlire.io"

# Reading Files
include:
  - _pages
exclude:
  - .circleci
  - _site
  - _config.yml
  - .forestry
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - renovate.json
  - develop.sh
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# PurgeCSS
css_dir: assets/css

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: page
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: wiki
    values:
      layout: page
      author_profile: true
      share: true
      toc: true
  - scope:
      path: ""
      type: games
    values:
      layout: page
      author_profile: true
      share: true
      toc: true
  - scope:
      path: ""
      type: books
    values:
      layout: page
      author_profile: false
      read_time: true
      share: true
      toc: true
collections:
  wiki:
    output: true
    permalink: /wiki/:path/
  games:
    output: true
    permalink: /games/:path/
  books:
    output: true
    permalink: /books/:path/
