source "https://rubygems.org"

# Jekyll
gem "jekyll", "= 4.2.0"

# Liquid-C
gem "liquid-c"

# Jekyll Plugins
gem "html-proofer", "= 3.19.1"
gem 'jekyll-feed', "= 0.15.1"
gem "jekyll-paginate", "= 1.1.0"
gem "jekyll-postcss", "= 0.4.0"
gem "jekyll-seo-tag", "= 2.7.1"
gem "jekyll-sitemap", "= 1.4.0"