---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: ''
  label: Pages
  create: all
  match: "**/*.md"
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _books
  label: Books
  create: all
  match: "**/*"
- type: directory
  path: _games
  label: Games
  create: all
  match: "**/*"
- type: directory
  path: _wiki
  label: Wiki
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
