---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "/*.md"
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _books
  label: Books
  create: all
  match: "**/*"
- type: directory
  path: _games
  label: Games
  create: all
  match: "**/*"
- type: directory
  path: _wiki
  label: Wiki
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: false
build:
  preview_output_directory: _site
  install_dependencies_command: bundle check --path=vendor/bundle || bundle install
    --path=vendor/bundle --jobs=4 --retry=3
  preview_docker_image: circleci/ruby:2.7.0-buster-node
  mount_path: "~/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site
  publish_env:
  - JEKYLL_ENV=production
  output_directory: _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
