---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "/*.md"
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _books
  label: Books
  create: all
  match: "**/*"
- type: directory
  path: _games
  label: Games
  create: all
  match: "**/*"
- type: directory
  path: _wiki
  label: Wiki
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
