---
new_page_extension: md
auto_deploy: true
admin_path: app/admin
webhook_url: 
sections:
- type: directory
  path: app/_pages
  label: Pages
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: app/_books
  label: Books
  create: all
  match: "**/*"
- type: directory
  path: app/_games
  label: Games
  create: all
  match: "**/*"
- type: directory
  path: app/_wiki
  label: Wiki
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=PRODUCTION
  preview_output_directory: _site
  install_dependencies_command: bundle check --path=vendor/bundle || bundle install
    --path=vendor/bundle --jobs=4 --retry=3
  preview_docker_image: forestryio/ruby:2.6-node12
  mount_path: "/srv"
  working_dir: "~/repo"
  instant_preview_command: bundle exec jekyll serve --config _config.yml --drafts
    --unpublished --future --port 8080 --host 0.0.0.0 -d _site
