- name: Ensure Nginx directory exists
  file: path=/etc/nginx state=directory

- name: Copy nginx tmpl file
  copy: src=nginx.tmpl dest=/etc/nginx/

- name: Install nginx systemd unit file
  template: src=nginx.service.j2 dest=/etc/systemd/system/nginx.service

- name: Start nginx
  systemd: state=restarted name=nginx daemon_reload=yes

- name: Install nginx-gen systemd unit file
  template: src=nginx-gen.service.j2 dest=/etc/systemd/system/nginx-gen.service

- name: Start nginx-gen
  systemd: state=restarted name=nginx-gen daemon_reload=yes

- name: Install nginx-letsencrypt systemd unit file
  template: src=nginx-letsencrypt.service.j2 dest=/etc/systemd/system/nginx-letsencrypt.service

- name: Start nginx-letsencrypt
  systemd: state=restarted name=nginx-letsencrypt daemon_reload=yes