- name: Ensure Traefik directory exists
  file: path=/etc/traefik state=directory

- name: Copy acme.json file
  copy: src=acme.json dest=/etc/traefik/acme.json mode=600

- name: Copy traefik.toml file
  copy: src=traefik.toml dest=/etc/traefik/traefik.toml

- name: Install traefik systemd unit file
  template: src=traefik.service.j2 dest=/etc/systemd/system/traefik.service

- name: Start traefik
  systemd: state=restarted name=traefik daemon_reload=yes enabled=yes